version: "3.8"
services:

 #catalogdb
  microservicenet.catalogdb:
    container_name: microservicenet.catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db

 #basketdb
  microservicenet.basketdb:
    container_name: microservicenet.basketdb
    restart: always
    ports:
      - "6379:6379"

 #discountdb
  microservicenet.discountdb:
    container_name: microservicenet.discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password12*
      - POSTGRES_DB=discountdb

 #identitydb
  microservicenet.identitydb:
    container_name: microservicenet.identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*

 #orderdb
  microservicenet.orderdb:
    container_name: microservicenet.orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*

 #notificationdb
  microservicenet.notificationdb:
    container_name: microservicenet.notificationdb
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - notificationdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*

 #rabbitmq
  microservicenet.rabbitmq:
    container_name: microservicenet.rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

 #catalog.api
  microservicenet.catalog.api:
    container_name: microservicenet.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=microservicenet.rabbitmq
      - IdentityServerURL=http://microservicenet.identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://microservicenet.catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - microservicenet.catalogdb
      - microservicenet.rabbitmq

 #identityserver.api
  microservicenet.identityserver.api:
    container_name: microservicenet.identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=microservicenet.identitydb,1433;Database=IdentityDb; User=sa; Password=Password12*"
    ports:
      - "5001:80"
    depends_on:
      - microservicenet.identitydb

 #basket.api
  microservicenet.basket.api:
    container_name: microservicenet.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://microservicenet.identityserver.api
      - RabbitMQUrl=microservicenet.rabbitmq
      - RedisSettings:Port=6379
      - RedisSettings:Host=microservicenet.basketdb
    ports:
      - "5013:80"
    depends_on:
      - microservicenet.basketdb
      - microservicenet.rabbitmq

 #photostock.api
  microservicenet.photostock.api:
    container_name: microservicenet.photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://microservicenet.identityserver.api
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: C:\Users\Muhammed\Desktop\photos
        target: /app/wwwroot/photos

 #discount.api
  microservicenet.discount.api:
    container_name: microservicenet.discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://microservicenet.identityserver.api
      - "ConnectionStrings:PostgreSql=User ID=admin; Password=Password12*; Server=microservicenet.discountdb; Port=5432;Database=discountdb;Integrated Security=true;Pooling=true"
    ports:
      - "5014:80"
    depends_on:
      - microservicenet.discountdb

 #fakepayment.api
  microservicenet.fakepayment.api:
    container_name: microservicenet.fakepayment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://microservicenet.identityserver.api
      - RabbitMQUrl=microservicenet.rabbitmq
    ports:
      - "5016:80"

 #order.api
  microservicenet.order.api:
    container_name: microservicenet.order.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://microservicenet.identityserver.api
      - RabbitMQUrl=microservicenet.rabbitmq
      - "ConnectionStrings:DefaultConnection=Server=microservicenet.orderdb,1444;Database=OrderDb; User=sa; Password=Password12*;TrustServerCertificate=True"
    ports:
      - "5015:80"
    depends_on:
      - microservicenet.orderdb
      - microservicenet.rabbitmq

 #gateway.api
  microservicenet.gateway.api:
    container_name: microservicenet.gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerURL=http://microservicenet.identityserver.api
    ports:
      - "5000:80"

  #notification.api
  microservicenet.notification.api:
    container_name: microservicenet.notification.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://microservicenet.identityserver.api
      - WebClient=http://microservicenet.aspnetcoremvc.web:5010/api/Notifications
      - RabbitMQUrl=microservicenet.rabbitmq
      - "ConnectionStrings:DefaultConnection=Server=microservicenet.notificationdb,1433;Database=NotificationDb; User=sa; Password=Password12*;TrustServerCertificate=True"
      - "ClientSettings:WebClientForUser:ClientId=WebMvcClientForUser"
      - "ClientSettings:WebClientForUser:ClientSecret=secret"
    depends_on:
      - microservicenet.notificationdb
      - microservicenet.rabbitmq
    ports:
      - "5020:80"


 #web.api 
  microservicenet.aspnetcoremvc.web:
    container_name: microservicenet.aspnetcoremvc.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceApiSettings:IdentityBaseUri=http://microservicenet.identityserver.api
      - ServiceApiSettings:GatewayBaseUri=http://microservicenet.gateway.api
    ports:
      - "5010:80"
    depends_on:
      - microservicenet.gateway.api
      - microservicenet.identityserver.api
      - microservicenet.catalog.api
      - microservicenet.basket.api
      - microservicenet.discount.api
      - microservicenet.order.api
      - microservicenet.photostock.api
      - microservicenet.fakepayment.api
      - microservicenet.notification.api

